name: Delete GitHub Package Version
author: David G. Moore, Jr., <david@dgmjr.io>
description: Deletes a version of a package from the GitHub Package Registry

branding:
  icon: git-merge
  color: green

inputs:
  repo:
    description: 'The repo to build'
    required: true
  git-token:
    description: 'The git token to use for the Packages repo'
    required: true
  package-name:
    description: 'The name of the package to delete'
    required: true
  package-version:
    description: 'The version of the package to delete'
    required: true
    default: 0.0.1
  organization:
    description: 'The organization that owns the repo'
    required: true
    default: dgmjr-io
  package-type:
    description: 'The type of package to delete'
    required: true
    default: nuget

runs:
  using: composite
  steps:
  - id: Install-Node-modules
    run: npm install
    shell: pwsh
    cwd: Scripts/ts
  - id: Delete-GitHub-Package-Version
    shell: pwsh
    run: ts-node-esm delete-github-package-version.ts --org ${{ inputs.organization }} --package-id ${{ inputs.package-name }} --version "${{ inputs.package-version }}" --type ${{ inputs.package-type }} --token ${{ inputs.git-token }}
    cwd: Scripts/ts
    env:
      GITHUB_TOKEN: ${{ inputs.git-token }}
